config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/edit', to: 'users#edit'
  patch 'users/:id',to: 'users#update',as: :user
  get 'users', to:'users#index'
  get 'users/new', to:'users#new'
  post 'users', to:'users#create'
  get 'posts', to:'posts#index'
  delete 'users/:id', to: 'users#destroy'
  get 'users/sign_in', to: 'users#sign_in'
  post 'users/create_session', to: 'users#create_session'
  get 'users/sign_out', to: 'users#sign_out'
  root :to => 'users#new'
  #patch 'users/:email',to: 'users#updatelink',as: :user



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many:posts
	has_many:comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index

  end
  def new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
	@users=User.all
	@my_variable="blah blah"
  end
  def new
	@user=User.new

  end
  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users=User.all
	@my_variable="blah blah"
	if cookies[:id]
		@signed_in_user= User.find(cookies[:user_id])
	end
  end
  def new
	@user=User.new

  end
  def create
	User.create(email: params[:user][:email],password: params[:user][:password],age: params[:user][:age],name: params[:user][:name])
	redirect_to action:'index'
  end
  def edit
	@user=User.find(params[:id])
  end
  
  def update
	@user=User.find(params[:id])
	@user.update(email: params[:user][:email],password: params[:user][:password],age: params[:user][:age],name: params[:user][:name])
	redirect_to action:'index'
  end
  def destroy
	@user=User.find(params[:id])
	@user.destroy
	redirect_to action:'index'
  end

  def toedit
	@user=User.find(params[:email])
  end
  def updatelink
	@user=User.find(params[:email])
	@user.update(email: params[:user][:email],password: params[:user][:password],age: params[:user][:age],name: params[:user][:name])
	redirect_to action:'index'
  end
  def sign_in
  end
  def sign_out
	if !cookies[:user_id].blank?
		cookies.delete(:user_id)
	end
	redirect_to action:'index'
  end
  def create_session
	u= User.find_by(email: params[:email], password: params[:password])
	if (u.blank?)
		return redirect_to action: 'sign_in'
	end
	cookies[:user_id]= u.id
	redirect_to action:'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basicjune</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div>
		<% if @signed_in_user %>
			<h4> welcome <%=@signed_in_user.email %> </h4>
		<% end %>
	</div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/users/edit.html.erb
<h1> Edit User Profile </h1>
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :age %>
	<%= f.number_field :age %>
	<br>
	<%= f.submit %>

<% end %>
<%=link_to 'Delete Account',@user, data: {:confirm=> 'Are you sure?'}, :method=> :delete %>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>
<% @users.each do |u| %>
<%= u.name %>
<% end %>
<%= link_to('Create New User', {controller=>'users', :action=>'new'}) %>

app/views/users/new.html.erb
<h1> User Sign Up </h1>
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<br>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :age %>
	<%= f.number_field :age %>
	<br>
	<%= f.submit %>
<% end %>

app/views/users/sign_in.html.erb
<h1> User Sign In </h1>

<%= form_tag users_create_session_path, method: :post do %>
	<%= label_tag :email %>
	<%= email_field_tag :email %>
	<br>
	
	<%= label_tag :password %>
	<%= password_field_tag :password %>

	<br>

	<%= submit_tag "sign in" %>
<% end %>

app/views/users/toedit.html.erb
<h1> Enter email </h1>
<%= form_for @user do |f| %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<br>

<% end %>